services:
  - type: web
    name: lstm-server
    env: python
    rootDir: DLModelBackend/Server/LSTMServer
    buildCommand: pip install --only-binary :all: -r requirements.txt 2>&1 || pip install -r requirements.txt
    startCommand: gunicorn server:app